# Generated by Django 3.0.8 on 2020-07-07 00:26

import django.core.validators
from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=200, validators=[main_app.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Name Must Only Contain Letters'), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Name Must Only Contain Letters'), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
