# Generated by Django 3.0.8 on 2020-07-07 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200707_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-z,A-Z]*$', 'Name Must Only Contain Letters'), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-z,A-Z]*$', 'Name Must Only Contain Letters'), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
